steps:
  # Step 1: Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      - '.'
    id: 'build-image'

  # Step 2: Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
    id: 'push-image'

  # Step 3: Cloud Run에 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      - '--platform=managed'
      - '--region=asia-northeast3'
      - '--allow-unauthenticated'
      - '--port=8000'
      - '--add-cloudsql-instances=kbeauty-landing-page:asia-northeast3:${_DB_INSTANCE}'
      - '--set-env-vars=DATABASE_URL=${_DATABASE_URL}'
      - '--set-env-vars=BASE_URL=${_BASE_URL}'
      - '--set-env-vars=GMAIL_ADDRESS=${_GMAIL_ADDRESS}'
      - '--set-env-vars=GMAIL_APP_PASSWORD=${_GMAIL_APP_PASSWORD}'
      - '--set-env-vars=SMTP_HOST=${_SMTP_HOST}'
      - '--set-env-vars=SMTP_PORT=${_SMTP_PORT}'
      - '--set-env-vars=GOOGLE_PLACES_API_KEY=${_GOOGLE_PLACES_API_KEY}'
      - '--set-env-vars=PAYPAL_CLIENT_ID=${_PAYPAL_CLIENT_ID}'
      - '--set-env-vars=PAYPAL_CLIENT_SECRET=${_PAYPAL_CLIENT_SECRET}'
      - '--set-env-vars=PAYPAL_API_BASE=${_PAYPAL_API_BASE}'
    id: 'deploy-cloud-run'

  # Step 4: Cloud Run Invoker 권한 부여 (allUsers)
  # Firebase Hosting rewrite는 unauthenticated request를 사용하므로 allUsers 필수
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - '${_SERVICE_NAME}'
      - '--region=asia-northeast3'
      - '--member=allUsers'
      - '--role=roles/run.invoker'
    id: 'grant-invoker-permission'

# 로그를 Cloud Logging에만 저장 (Storage bucket 사용 안 함)
options:
  logging: CLOUD_LOGGING_ONLY

# 빌드된 이미지
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'

# 타임아웃 설정 (20분)
timeout: '1200s'
